org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1

minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.211
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13

mod_id=appdyenamics
mod_name=Applied Dyenamics
mod_license=GNU LGPL 3.0
mod_version=1.21.1-1.0.1
mod_group_id=lu.kolja
mod_authors=Kolja
mod_description=Adds all colors from the Dyenamic mod to AE2

ae2_version=19.2.17