org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=appdyenamics
mod_name=Applied Dyenamics
mod_license=GNU LGPL 3.0
mod_version=1.20.1-1.0.0
mod_group_id=lu.kolja
mod_authors=Kolja
mod_description=Adds all colors from the Dyenamic mod to AE2

ae2_version=15.4.9
dyenamics_version=1.20.1-3.2.0