
modLoader = "kotlinforforge"
loaderVersion = "${loader_version_range}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://github.com/ko-lja/applied-dyenamics"
logoFile="appdyenamics_logo.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "dyenamics"
type = "required"
ordering = "NONE"
side = "BOTH"